name: 构建libtorrent-rasterbar镜像
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建libtorrent-rasterbar镜像
    env:
      DOCKER_BUILDKIT: 1
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      IMAGE_NAME: libtorrent-rasterbar
      DOCKERFILE_NAME: Dockerfile2
      DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/libtorrent-rasterbar
      BUILDX_ARCH: linux/amd64
    steps:
      - 
        name: 检出
        uses: actions/checkout@master

      - 
        name: 设置QEMU
        uses: docker/setup-qemu-action@v1

      - 
        name: 设置Buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: 登陆DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: 构建并推送到Dockerhub
        run: |
          LIBTORRENT_VERSION=$(curl -s https://api.github.com/repos/arvidn/libtorrent/tags | jq -r .[]."name" | grep -vi "rc" | grep -m 1 "v2." | sed "s/v//")
          cd ${IMAGE_NAME}
          docker buildx build \
            --progress "plain" \
            --no-cache \
            --output "type=image,push=true" \
            --platform "${BUILDX_ARCH}" \
            --build-arg "LIBTORRENT_VERSION=${LIBTORRENT_VERSION}" \
            --tag "${DOCKERHUB_REPOSITORY}:${LIBTORRENT_VERSION}" \
            --file ${DOCKERFILE_NAME} \
            .