name: 构建qBittorrent镜像
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建qBittorrent镜像
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      CONTEXT: qbittorrent
      DOCKERFILE_NAME: Dockerfile.GithubAction
      DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/qbittorrent
      BUILDX_ARCH: linux/amd64,linux/arm64,linux/arm/v7
    steps:
      - 
        name: 检出
        uses: actions/checkout@master

      - 
        name: 设置QEMU
        uses: docker/setup-qemu-action@v1

      - 
        name: 设置Buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: 登陆DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - 
        name: 设置缓存
        uses: actions/cache@v2
        id: buildx-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx

      - 
        name: 构建并推送镜像
        run: |
          cd ${CONTEXT}
          bash buildx-github-action.sh
          