name: 更新qBittorrent介绍
on:
  push:
    branches:
      - master
    paths:
      - qbittorrent/readme.md
      - .github/workflows/qbittorrent-dockerhub-description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2

    - 
      name: Update DockerHub Readme
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: nevinee/qbittorrent
        readme-filepath: ./qbittorrent/readme.md
