name: 构建qBittorrent-IYUU镜像

on:
  workflow_dispatch:
    inputs:
      version:
        description: '要构建的版本，仅支持正式版'
        required: true
        default: ''

env:
  ## 镜像名，也是git仓库中的文件夹名
  IMAGE_NAME: qbittorrent
  ## Dockerfile文件名称，在这里修改
  DOCKERFILE_NAME2: Dockerfile.iyuu

jobs:
  build2:
    runs-on: ubuntu-latest
    name: 并行构建QB-IYUU
    timeout-minutes: 10
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
           
      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Set Up Cache
        uses: actions/cache@v2
        id: buildx-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
      
      - 
        name: Buildx
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.IMAGE_NAME }}
          file: ${{ env.IMAGE_NAME }}/${{ env.DOCKERFILE_NAME2 }}
          platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/ppc64le,linux/s390x
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}-iyuu
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:iyuu