name: 构建qBtest镜像
on:
  workflow_dispatch:

jobs:
  base:
    runs-on: ubuntu-latest
    name: 定义架构
    env:
      IMAGE_NAME: qbtest
      DOCKERFILE_NAME: Dockerfile.GithubAction
    outputs:
      full_version: ${{ steps.base.outputs.full_version }}
      multitags: ${{ steps.base.outputs.multitags }}
      build_args: ${{ steps.base.outputs.build_args }}
      matrix: ${{ steps.base.outputs.matrix }}
      image_name: ${{ env.IMAGE_NAME }}
      dockerfile_name: ${{ env.DOCKERFILE_NAME }}
    steps:
      - 
        name: Set Matrix
        id: base
        run: |
          FULL_VERSION=$(curl -s https://api.github.com/repos/qbittorrent/qBittorrent/tags | jq -r .[]."name" | grep -m1 -E "release-([0-9]\.?){3,4}$" | sed "s/release-//")
          DOCKERHUB_REPOSITORY="${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}"

          PATCH_VERSION=$(printf "${FULL_VERSION}" | cut -d '.' -f 1-3)
          MINOR_VERSION=$(printf "${FULL_VERSION}" | cut -d '.' -f 1-2)
          MAJOR_VERSION=$(printf "${FULL_VERSION}" | cut -d '.' -f 1)

          if [[ ${FULL_VERSION} == ${PATCH_VERSION} ]]; then \
            MULTITAGS="${MAJOR_VERSION} ${MINOR_VERSION} ${FULL_VERSION} latest"; \
          else \
            MULTITAGS="${MAJOR_VERSION} ${MINOR_VERSION} ${PATCH_VERSION} ${FULL_VERSION} latest"; \
          fi

          echo ::set-output name=full_version::${FULL_VERSION}
          echo ::set-output name=multitags::${MULTITAGS}
          echo ::set-output name=build_args::QBITTORRENT_VERSION=${FULL_VERSION}
          echo "::set-output name=matrix::{\"architecture\":[\"linux/386\", \"linux/amd64\"]}"

  build:
    needs: base
    runs-on: ubuntu-latest
    name: 并行构建
    strategy:
      matrix: ${{ fromJSON(needs.base.outputs.matrix) }}
      max-parallel: 2
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      -
        name: Prepare
        id: prepare
        run: |
          FULL_VERSION="${{ needs.base.outputs.full_version }}"
          IMAGE_NAME="${{ needs.base.outputs.image_name }}"
          DOCKERFILE_NAME="${{ needs.base.outputs.dockerfile_name }}"
          DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
          ARCH="${{ matrix.architecture }}"
          
          ## 修改LIBTORRENT的基础版本
          if [[ ${FULL_VERSION} == 4.3* ]]; then \
            perl -i -pe "s|LIBTORRENT_MAJOR_VERSION|1|" ${IMAGE_NAME}/${DOCKERFILE_NAME}; \
          else \
            perl -i -pe "s|LIBTORRENT_MAJOR_VERSION|2|" ${IMAGE_NAME}/${DOCKERFILE_NAME}; \
          fi

          TAGS="${DOCKER_USERNAME}/${IMAGE_NAME}:${FULL_VERSION}-$(echo ${ARCH} | perl -pe '{s|linux/||g; s|/|-|g}')"

          echo ::set-output name=tags::${TAGS}

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - 
        name: Buildx
        uses: docker/build-push-action@v2
        with:
          context: ${{ needs.base.outputs.image_name }}
          file: ${{ needs.base.outputs.image_name }}/${{ needs.base.outputs.dockerfile_name }}
          platforms: ${{ matrix.architecture }}
          push: true
          build-args: ${{ needs.base.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tags }}

  maintain:
    needs: [base, build]
    runs-on: ubuntu-latest
    name: 信息维护
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - 
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - 
        name: Create And Push Manifest
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          DOCKERHUB_REPOSITORY="${{ secrets.DOCKER_USERNAME }}/${{ needs.base.outputs.image_name }}"
          ALL_ARCH=( $(echo "${{ needs.base.outputs.matrix }}" | jq -r .architecture[] | perl -pe '{s|linux/||g; s|/|-|g}') )
          MULTITAGS="${{ needs.base.outputs.multitags }}"
          
          IMAGES=()
          for arch in ${ALL_ARCH[@]}; do \
            IMAGES+=( "${DOCKERHUB_REPOSITORY}:${{ needs.base.outputs.full_version }}-${arch}" ); \
          done

          for tag in ${MULTITAGS}; do \
            docker manifest create "${DOCKERHUB_REPOSITORY}:${tag}" "${IMAGES[@]}"; \
          done

          for tag in ${MULTITAGS}; do \
            docker manifest push --purge "${DOCKERHUB_REPOSITORY}:${tag}"; \
          done

      - 
        name: Update DockerHub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ needs.base.outputs.image_name }}
          readme-filepath: ./${{ needs.base.outputs.image_name }}/readme.md
          short-description: ${{ needs.base.outputs.image_name }} ${{ needs.base.outputs.full_version }}：全平台, 下载完成通知, 自动分类, tracker错误标记, 宕机通知, 日志显示

  notify:
    needs: [base, build, maintain]
    if: always()
    runs-on: ubuntu-latest
    name: 发送通知
    steps:    
      - 
        name: Send All Success Notify
        if: ${{ needs.build.result == 'success' && needs.maintain.result == 'success' }}
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DD_BOT_TOKEN }}
          secret: ${{ secrets.DD_BOT_SECRET }}
          body: |
            {
              "msgtype": "text",
              "text": {
                "content": "镜像构建并维护成功\n\n${{ secrets.DOCKER_USERNAME }}/${{ needs.base.outputs.image_name }}镜像构建成功，信息维护成功\n版本：${{ needs.base.outputs.full_version }}\n链接：https://hub.docker.com/repository/docker/${{ secrets.DOCKER_USERNAME }}/${{ needs.base.outputs.image_name }}"
              }
            }
      - 
        name: Send Only Build Success Notify
        if: ${{ needs.build.result == 'success' && needs.maintain.result != 'success' }}
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DD_BOT_TOKEN }}
          secret: ${{ secrets.DD_BOT_SECRET }}
          body: |
            {
              "msgtype": "text",
              "text": {
                "content": "镜像构建成功\n\n${{ secrets.DOCKER_USERNAME }}/${{ needs.base.outputs.image_name }}镜像构建成功，但信息维护失败了\n版本：${{ needs.base.outputs.full_version }}\n链接：https://hub.docker.com/repository/docker/${{ secrets.DOCKER_USERNAME }}/${{ needs.base.outputs.image_name }}"
              }
            }
      
      - 
        name: Send Failure Notify
        if: ${{ needs.build.result == 'failure' }}
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DD_BOT_TOKEN }}
          secret: ${{ secrets.DD_BOT_SECRET }}
          body: |
            {
              "msgtype": "text",
              "text": {
                "content": "镜像构建失败\n\n${{ secrets.DOCKER_USERNAME }}/${{ needs.base.outputs.image_name }}镜像构建失败\n版本：${{ needs.base.outputs.full_version }}\n链接：https://hub.docker.com/repository/docker/${{ secrets.DOCKER_USERNAME }}/${{ needs.base.outputs.image_name }}"
              }
            }