name: 同步libtorrent仓库到Gitee

on:
  schedule:
    - cron:  '16 6,18 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: mirror-libtorrent

concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:arvidn/libtorrent.git"
          destination-repo: "git@gitee.com:evine/libtorrent.git"