name: 构建Tieba-Cloud-Sign镜像

on:
  workflow_dispatch:
  repository_dispatch:
    types: tieba-cloud-sign

env:
  ## 镜像名，也是git仓库中的文件夹名
  IMAGE_NAME: tieba-cloud-sign
  ## Dockerfile文件名称，在这里修改
  DOCKERFILE_NAME: Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建镜像
    timeout-minutes: 30
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Set Up Cache
        uses: actions/cache@v2
        id: buildx-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
      
      - 
        name: Buildx
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.IMAGE_NAME }}
          file: ${{ env.IMAGE_NAME }}/${{ env.DOCKERFILE_NAME }}
          platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
